### ISSUE TITLE
TODO list for v6

### ISSUE THREAD

**Issue by jskeet** [dotnet/csharpstandard#183]
This is hopefully the order in which we do things, but there may well be some overlap. Gating discussed later

- [ ] (Bill) Create GitHub teams for Repo Admin (Jon, Bill), and Committee Members (The committee members)
  - The Admin team would have Admin access, the committee team would have Write access.
  - Note on committee members: We have a number of inactive members. Should they be added to the Committee Members team?
- [x] (Bill) Configure branch protection for working branches.  I expect to configure:
  - Require pull request review before merging.
  - Require all status checks to pass before merging (see below)
  - Include administrators in branch protection rules.
  - Note: These rules will enforce that none of us accidentally make changes to the standard that haven't been reviewed and approved.
- [x] (Bill) Configure status checks.
  - Run the section renumbering tool on each PR to fix section numbers.
  - Run the Word converter on each PR to make sure it generates a valid Word file.
  - Validate ANTLR grammar (when possible)
- [x] (Jon) Review current labels & create lablels for C# 6 (and beyond) features.
- [ ] (Jon) Complete Word converter fixes
- [x] (Jon / Rex) Review template (fonts etc)
- [x] (Bill) Create new repository
  - Top-level folders of `standard`, `tools` and `organization` (last name very much up for discussion - things like agendas, minutes; docs, but not *documentation*)
- [x] (Bill) Create new branches in new repo with appropriate history - *exact* branch names TBD
- [x] (Bill) Create PRs for C# 6, one per top-level clause, in new repo - ideally with just the C# 6 changes in, i.e. not the changes we've already reviewed to fix issues, but that might happen too.
- [x] (Jon) Migrate open issues over the new repo, automatically where feasible, but manually where we need to remove some history
  - This should include setting a milestone to indicate whether they can be postponed past C# 6
  - Closed issues will not be migrated - we probably want to either export all the existing issues, or keep the current repo available to us forever, to avoid losing the "I remember we've talked about this before" option
- [ ] (Bill) Move repo to `dotnet` organization
- [ ] (All) Review the PRs, discussing them in meetings where there are points of disagreement
- [ ] (All) Create, review and merge PRs that fix the migrated issues

The only dependencies here (I think) are:

- We can't migrate anything until the repo exists
- We shouldn't move the repo to `dotnet` until all the issues are migrated (as moving issues cross-organization is tricky)
